{
  imports = [
    ./colorscheme.nix
    ./forgejo-runner.nix
    ./maddy.nix
    ./matrix.nix
    ./mc-whitelist.nix
    ./navidrome.nix
    ./networking.nix
    ./network-topology.nix
    ./remote-builds.nix
    ./sana-website.nix
    ./searxng.nix
    ./slskd.nix
    ./wikipedia-mirror.nix
    ./ssh.nix
    ./wokeforum.nix
    ./zsh.nix
  ];
}
