# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.initrd.systemd.enable = true;
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5326bb23-7944-4120-b758-5a656f43e389";
    fsType = "ext4";
  };

  fileSystems."/tmp" = {
    device = "none";
    fsType = "tmpfs";
    options = ["defaults" "size=1G" "mode=777"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3006-C199";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/home";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."home" = {
    device = "/dev/disk/by-uuid/bc595b08-03e2-4698-adc1-a019ec5b421d";
    gpgCard = {
      encryptedPass = "/boot/keyfile.bin.gpg";
      publicKey = "/boot/pubkey.asc";
    };
    crypttabExtraOpts = [
      "fido2-device=auto"
    ];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
